#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
MYDIR="$(cd "$(dirname -- "$0")"; pwd)"
MYNAME="$(basename -- "$0")"
MYSELF="$MYDIR/$MYNAME"
RDDMGR="$MYDIR"

if [ ! -f "$RDDMGR/lib/vendor/nulib/php/load.sh" ]; then
    if [ -f "$RDDMGR/lib/build.env" ]; then config="$RDDMGR/lib/build.env"
    else config="$RDDMGR/lib/.build.env.dist"
    fi
    "$RDDMGR/lib/sbin/rundk" -0 --unless-exists -c "$config" || exit 1
fi
"$MYDIR/lib/sbin/bootstrap" && source "$MYDIR/lib/vendor/nulib/php/load.sh" || exit 1
source "$RDDMGR/lib/functions.sh" || exit 1

check=auto
action=
init=
Reinit=
init_auto=1
InitChecks=
InitNetworks=
Recreate=
BuildBefore=1
args=(
    "gestionnaire d'ateliers"
    " -c WKSDIR FILES..."
    --bootstrap action=bootstrap "++Mettre à jour les outils en lançant de nouveau lib/sbin/bootstrap"
    --check check=1 "++Vérifier les ateliers avant de lancer une commande"
    --no-check check= "++Ne pas vérifier les ateliers avant de lancer une commande"
    -0,--init init=1 "Initialiser l'environnement docker nécessaire aux ateliers"
    --init-checks '$init_auto=; InitChecks=1' "++Faire uniquement la vérification des pré-requis"
    --init-networks '$init_auto=; InitNetworks=1' "++Faire uniquement l'initialisation des réseaux"
    -l,--lists action=list "Lister les ateliers"
    -c,--create action=create "Créer un nouvel atelier.
Il faut fournir comme argument supplémentaire une ou plusieurs des informations suivantes:
- [create=]WKSDIR -- le nom de l'environnement à créer
- [source=]SOURCE_WKSDIR -- un atelier depuis lequel copier les fichiers s'ils ne sont pas spécifiés. Doit être mentionné après WKSDIR
- [shared=]SHARED_DIR -- chemin vers un répertoire contenant les répertoires rdd-tools, rdd-tools-pivot, fichiers_init_et_transcos téléchargés depuis l'espace partagé $SHARED_URL?p=/RDD&mode=list
- [version=]VERSION -- version des fichiers à considérer. peut être de la forme 23.0.0 ou 0.1.0-dev.824
- SOURCE -- une valeur parmi apogee, scolarix, sve ou vierge permettant de sélectionner automatiquement le bon fichier d'initialisation et de transcodification dans SHARED_DIR
- [image=]rdd-tools_VERSION.tar -- image docker à importer
- [env=]mypegase_VERSION.env -- fichier d'environnement
- [pivot=]rdd-tools-pivot_VERSION.tar.gz -- définition de la base pivot
- RDD-scripts-externes_VERSION.zip -- scripts externes à installer
- RDD-init-habilitations-personnes_VERSION.zip -- fichier d'initialisation des personnes et des habilitations
- RDD-init-transco-SOURCE_VERSION.zip -- fichier d'initialisation et de transcodification. un seul fichier (et donc une seule SOURCE) doit être sélectionné"
    --recreate Recreate=1 "++Forcer la (re)création de l'atelier même s'il existe déjà"
    -d,--delete action=delete "Supprimer un atelier"
    -s,--start action=start "Démarrer traefik, pgAdmin, frontal, et les services des ateliers spécifiés ou à défaut de l'atelier par défaut"
    -k,--stop action=stop "Arrêter traefik, pgAdmin, frontal, et les services des ateliers spécifiés, ou à défaut de TOUS les ateliers"
    -r,--restart action=restart "(Re)démarrer traefik, pgAdmin, frontal, et les services des ateliers spécifiés ou à défaut de l'atelier par défaut"
    --no-build BuildBefore= "++Ne pas (re)construire les images avant de démarrer les services"
)
parse_args "$@"; set -- "${args[@]}"

verifix_config
load_config

if [ -n "$init" ]; then
    [ -n "$action" ] || action=none
    [ "$check" == auto ] && check=
    if [ -n "$init_auto" ]; then
        InitChecks=1
        InitNetworks=1
    fi

    init_system
fi

[ -n "$action" ] || action=start
if [ "$check" == auto ]; then
    # vérification auto, sauf pour liste
    case "$action" in
    list) check=;;
    *) check=1;;
    esac
fi
[ -n "$check" ] && check_system

case "$action" in
none) ;;
bootstrap) "$RDDMGR/lib/sbin/bootstrap" --force "$@";;
list) list_workshops;;
create) create_workshop "$@";;
delete) delete_workshop "$@";;
start) start_services "$@";;
stop) stop_services "$@";;
restart) restart_services "$@";;
*) die "$action: action non implémentée";;
esac
