#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
MYDIR="$(dirname -- "$0")"
"$MYDIR/bootstrap" && source "$MYDIR/../vendor/nulib/php/load.sh" || exit 1
RDDMGR="${MYDIR%/*}"; RDDMGR="${RDDMGR%/*}"

args=(
    "refaire le fichier secrets.conf"
)
parse_args "$@"; set -- "${args[@]}"

cd "$RDDMGR"

if [ -f config/secrets.conf ]; then
    ebanner "Le fichier secrets.conf existe déjà

Si vous le regénérez, il faudra recréer TOUTES les bases pivot et les services traefik et pgadmin"
    ask_yesno "Voulez-vous le regénérer le fichier config/secrets.conf?" N || die
fi

einfo "génération du fichier config/secrets.conf"
mkdir -p config
awk <lib/templates/secrets.conf >config/secrets.conf '{
  if ($0 ~ /XXXRANDOMXXX/) {
    LETTERS = "AZERTYUIOPQSDFGHJKLMWXCVBNazertyuiopqsdfghjklmwxcvbn0123456789"
    max = length(LETTERS)
    password = ""
    for (i = 0; i < 16; i++) {
      password = password substr(LETTERS, int(rand() * max), 1)
    }
    sub(/XXXRANDOMXXX/, password)
  }
  print
}'
chmod 600 config/secrets.conf
