#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
MYDIR="$(dirname "$0")"
"$MYDIR/../lib/sbin/bootstrap" && source "$MYDIR/../lib/vendor/nulib/php/load.sh" || exit 1
RDDMGR="${MYDIR%/*}"
WKSDIR="$MYDIR"
source "$RDDMGR/lib/functions.sh" || exit 1

action=rddtools
BuildBefore=1
Envname=
Debug=
CleanAfter=
args=(
    "front-end pour rddtools"
    "\
[-e Envname] commands...
-l                       -- lister les environnements existants
-c [suffix]              -- créer un nouvel environnement
-C Envname [suffix]      -- dupliquer un environnement existant
-K Envname               -- supprimer un environnement

Les noms d'environnement sont *toujours* préfixés du nom de l'instance PEGASE correspondante.
En cas de création ou de duplication de plusieurs environnements pour une même instance PEGASE, [suffix] permet de les distinguer"
    -s,--start action=start "Démarrer la base pivot"
    -k,--stop action=stop "Arrêter la base pivot"
    -r,--restart action=restart "Redémarrer la base pivot"
    --no-build BuildBefore= "++Ne pas (re)construire les images avant de démarrer les services"
    -l,--list action=list "Lister les environnements"
    -c,--create action=create "Créer un nouvel environnement"
    -C,--duplicate action=duplicate "Dupliquer un environnement"
    -K,--delete action=delete "Supprimer un environnement"
    -m,--edit action=edit "Editer le fichier d'environnement"
    -e:,--env Envname= "Spécifier l'environnement à utiliser"
    -d,--debug Debug=1 "Lancer la tâche en mode debug (debug_job=O)"
    -g,--clean-after CleanAfter=1 "++Indiquer s'il faut supprimer l'environnement système après exécution de la tâche"
)
parse_args "$@"; set -- "${args[@]}"

load_config "" "$WKSDIR/.env"

case "$action" in
start) start_pivotbdd "$@";;
stop) stop_pivotbdd "$@";;
restart) restart_pivotbdd "$@";;
list) list_envs "$@";;
create) create_env "$@";;
duplicate) duplicate_env "$@";;
delete) delete_env "$@";;
edit) edit_env "$@";;
rddtools) run_rddtools "$@";;
*) die "$action: action non implémentée";;
esac
